create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key default gen_random_uuid(),
  nickname text not null,
  nickname_key text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  nickname_changed_at timestamptz,
  device_hash text not null,
  recovery_hash text not null,
  last_seen_at timestamptz not null default now(),
  flagged boolean not null default false
);

create unique index if not exists profiles_nickname_key_uidx on public.profiles (nickname_key);
create unique index if not exists profiles_device_hash_uidx on public.profiles (device_hash);

create table if not exists public.reserved_nicknames (
  nickname_key text primary key,
  reserved_until timestamptz not null,
  reason text not null default 'rename'
);

create table if not exists public.leaderboard_scores (
  profile_id uuid primary key references public.profiles(id) on delete cascade,
  nickname text not null,
  captain_score bigint not null default 0,
  total_gold_earned numeric not null default 0,
  unlocked_zone_count integer not null default 1,
  boss_defeated integer not null default 0,
  ascension_count integer not null default 0,
  codex_stars integer not null default 0,
  discovered_count integer not null default 0,
  equipment_unique integer not null default 0,
  total_node_levels integer not null default 0,
  highest_zone text not null default 'shallow',
  last_seen_at timestamptz not null default now(),
  flagged boolean not null default false
);

create index if not exists leaderboard_captain_idx on public.leaderboard_scores (captain_score desc, last_seen_at asc);
create index if not exists leaderboard_gold_idx on public.leaderboard_scores (total_gold_earned desc, last_seen_at asc);
create index if not exists leaderboard_depth_idx on public.leaderboard_scores (unlocked_zone_count desc, last_seen_at asc);
create index if not exists leaderboard_boss_idx on public.leaderboard_scores (boss_defeated desc, last_seen_at asc);
create index if not exists leaderboard_ascension_idx on public.leaderboard_scores (ascension_count desc, last_seen_at asc);

create table if not exists public.score_snapshots (
  id bigint generated by default as identity primary key,
  profile_id uuid not null references public.profiles(id) on delete cascade,
  submitted_at timestamptz not null default now(),
  captain_score bigint not null,
  metrics jsonb not null,
  status text not null default 'accepted',
  constraint score_snapshots_status_check check (status in ('accepted', 'flagged', 'rejected'))
);

alter table public.profiles enable row level security;
alter table public.reserved_nicknames enable row level security;
alter table public.leaderboard_scores enable row level security;
alter table public.score_snapshots enable row level security;

drop policy if exists "public leaderboard summary" on public.leaderboard_scores;
create policy "public leaderboard summary" on public.leaderboard_scores for select using (flagged = false);

drop policy if exists "public reserved nickname check" on public.reserved_nicknames;
create policy "public reserved nickname check" on public.reserved_nicknames for select using (reserved_until > now());

create or replace function public.calculate_captain_score(
  p_gold numeric,
  p_zones integer,
  p_bosses integer,
  p_ascensions integer,
  p_codex_stars integer,
  p_discovered integer,
  p_equipment integer,
  p_node_levels integer
) returns bigint language sql immutable as $$
  select greatest(0, floor(
    ln(greatest(10, coalesce(p_gold, 0)) + 10) * 120 / ln(10) +
    coalesce(p_zones, 0) * 350 +
    coalesce(p_bosses, 0) * 500 +
    coalesce(p_ascensions, 0) * 900 +
    coalesce(p_codex_stars, 0) * 60 +
    coalesce(p_discovered, 0) * 30 +
    coalesce(p_equipment, 0) * 35 +
    coalesce(p_node_levels, 0) * 8
  ))::bigint;
$$;