const cors = { "Access-Control-Allow-Origin": "*", "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type", "Access-Control-Allow-Methods": "POST, OPTIONS" };
const enc = new TextEncoder();
const hash = async (value) => Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256", enc.encode(value)))).map((b) => b.toString(16).padStart(2, "0")).join("");
const json = (body, status = 200) => new Response(JSON.stringify(body), { status, headers: { ...cors, "Content-Type": "application/json" } });
Deno.serve(async (request) => {
  if (request.method === "OPTIONS") return new Response("ok", { headers: cors });
  if (request.method !== "POST") return json({ error: "method" }, 405);
  const { nickname, deviceToken } = await request.json();
  if (!/^[\u4e00-\u9fa5A-Za-z0-9_]{2,12}$/.test(nickname || "")) return json({ error: "invalid_nickname" }, 400);
  const key = nickname.toLowerCase();
  const url = Deno.env.get("SUPABASE_URL");
  const service = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");
  const headers = { apikey: service, Authorization: `Bearer ${service}`, "Content-Type": "application/json", Prefer: "return=representation" };
  const reserved = await fetch(`${url}/rest/v1/reserved_nicknames?nickname_key=eq.${encodeURIComponent(key)}&select=nickname_key`, { headers });
  if ((await reserved.json()).length) return json({ error: "nickname_reserved" }, 409);
  const existing = await fetch(`${url}/rest/v1/profiles?nickname_key=eq.${encodeURIComponent(key)}&select=id`, { headers });
  if ((await existing.json()).length) return json({ error: "nickname_taken" }, 409);
  const recoveryCode = crypto.randomUUID().replaceAll("-", "").slice(0, 12).toUpperCase();
  const rows = await fetch(`${url}/rest/v1/profiles`, { method: "POST", headers, body: JSON.stringify({ nickname, nickname_key: key, device_hash: await hash(deviceToken), recovery_hash: await hash(recoveryCode) }) }).then((r) => r.json());
  const profile = rows[0];
  await fetch(`${url}/rest/v1/leaderboard_scores`, { method: "POST", headers, body: JSON.stringify({ profile_id: profile.id, nickname, last_seen_at: new Date().toISOString() }) });
  return json({ profile: { id: profile.id, nickname: profile.nickname, nicknameKey: profile.nickname_key, createdNicknameAt: Date.parse(profile.created_at) }, recoveryCode });
});